### ISSUE TITLE
sf 1.7.12 not building in brew due to mod file (golang modules)

### ISSUE THREAD

**Issue by richardlehane** [richardlehane/homebrew-digipres#4]
Reported by @retokromer:

This gives an error on my end:

==> go build -tags brew github.com/richardlehane/siegfried/cmd/sf
Last 15 lines from /Users/test/Library/Logs/Homebrew/siegfried/01.go:
2019-06-17 18:31:12 +0200

go
build
-tags
brew
github.com/richardlehane/siegfried/cmd/sf
 
$GOPATH/go.mod exists but should not

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/richardlehane/homebrew-digipres/issues

**Comment by richardlehane** [comment]
fixed by #63af101  (got rid of GOPATH variable and use the -mod=vendor switch)

**Comment by retokromer** [comment]
@richardlehane Thank you!
